[package]
name = "day__"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
libaoc.workspace = true

[lints]
workspace = true
